[package]
name = "yggify"
version = "0.1.0"
edition = "2018"
authors = ["Salem Yaslem <s@sy.sa>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
